[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "d2h"
version = "0.1.0"
description = "D2H Isaac Lab Environment"
requires-python = ">=3.10"
dependencies = [
    "diffusers>=0.37.1",
    "dynamixel-sdk==4.0.5",
]

[project.optional-dependencies]
deployment = ["rich", "pyserial", "PyYAML"]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
